### ISSUE TITLE
when compiling sqlpp11_mysql_tests I get link errors

### ISSUE THREAD

**Issue by juandent** [rbock/sqlpp11#428] opened 2022-03-11 15:43 UTC
I am getting:

mysqlclient.lib(libmysql.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in Json.obj
mysqlclient.lib(libmysql.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MDd_DynamicDebug' in Json.obj

I downloaded mysql/mysql-server but could not build it because could not find SSL

Help appreciated

**Comment by juandent** [comment] 2022-03-11 15:44
I installed MySQL community edition but it does not have debug libraries...

**Comment by rbock** [comment] 2022-03-11 19:41
You are on Windows? I have zero experience with that, but this looks promising:

https://dev.mysql.com/downloads/installer/

**Comment by juandent** [comment] 2022-03-11 20:44
yes I am in Windows.
Thank you, but this installer does not provide the debug libraries. I have the source code from mysql/mysql-server and using CMAKE-GUI it does not find the SSL although I installed it... Did you compile  MYSQL from source code in your OS? which OS do you use?

**Comment by juandent** [comment] 2022-03-11 20:49
does sqlpp11 support dynamic from or with statements?

**Comment by rbock** [comment] 2022-03-12 07:33
I am using Ubuntu Linux. It has separate repositories for debug symbols, but I haven't used those yet. I would probably compile from source.

That being said, I guess that stackoverflow would be a better place, if you can shrink the problem to a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example). This would probably not include sqlpp11, since it seems unlikely to me that your build issues are linked to it.

I am therefore closing this issue.

**Closed by rbock** 2022-03-12 07:33 UTC
