### ISSUE TITLE
Assertion failure in Sqlpp11MySQLSampleTest when using debug version of MySQL

### ISSUE THREAD

**Issue by juandent** [rbock/sqlpp11#109] opened 2016-08-18 20:07 UTC
Hi Roland,
I have been too busy with other work and just downloaded the latest versions of sqlpp11 and sqlpp11-connector-mysql, and to my surprise the bug related to the buffer length being 0 is still present.

This bug if you recall, occurred in the file `libmysql.c` line 4078 of the MySQL latest source. It reads:

```C++
DBUG_ASSERT(param->buffer_length != 0);
```

I had provided a proposal that modified 
```C++
void bind_result_t::_bind_text_result(size_t index, const char** value, size_t* len)
```

by adding the code inside #ifdef JDH:

```C++
      detail::result_meta_data_t& meta_data = _handle->result_param_meta_data[index];
      meta_data.index = index;
      meta_data.len = len;
      meta_data.is_null = nullptr;
      meta_data.text_buffer = value;
#define JDH
#ifdef JDH
	  meta_data.bound_text_buffer = std::vector<char>(254);
#endif
      MYSQL_BIND& param = _handle->result_params[index];
      param.buffer_type = MYSQL_TYPE_STRING;
      param.buffer = meta_data.bound_text_buffer.data();
      param.buffer_length = meta_data.bound_text_buffer.size();
      param.length = &meta_data.bound_len;
      param.is_null = &meta_data.bound_is_null;
      param.is_unsigned = false;
      param.error = &meta_data.bound_error;
```

Have you reached at a better solution?

Best regards,
Juan Dent

**Comment by rbock** [comment] 2016-08-19 05:01
Hi Juan,

I admit I forgot to deal with that, especially since the current code is in line with the documentation of MySQL, if I remember correctly. I hope to find time to look into it soon.

Thanks for reminding me!

Best,

Roland

**Comment by rbock** [comment] 2016-09-06 14:36
Closing this one, as the issue is solved in the mysql connector.

**Closed by rbock** 2016-09-06 14:36 UTC
