### ISSUE TITLE
Unable to compile (with HinnantDate) in CMake

### ISSUE THREAD

**Issue by biot023** [rbock/sqlpp11#137] opened 2017-01-31 08:10 UTC
Hi -- I'm trying to install sqlpp11 into my project as a submodule, and have added HinnantDate/date, sqlpp11, and sqlpp11-connector-postgresql as git submodules. I've added them to a vendor/ subdirectory of the main source directory.
I've added them to my CMakeFiles.txt file like this:

    set(VENDOR_DIR ${CMAKE_SOURCE_DIR}/vendor)
    set(Sqlpp11_DIR ${VENDOR_DIR}/sqlpp11/cmake)
    add_subdirectory(vendor/sqlpp11)
    add_subdirectory(vendor/sqlpp11-connector-postgresql)

However, when I try to run `cmake ..` (from a build subdirectory), I get the following error:

> CMake Error at /usr/local/share/cmake-3.7/Modules/CMakeFindDependencyMacro.cmake:55 (find_package):
>   By not providing "FindHinnantDate.cmake" in CMAKE_MODULE_PATH this project
>   has asked CMake to find a package configuration file provided by
>   "HinnantDate", but CMake did not find one.
> 
>   Could not find a package configuration file provided by "HinnantDate" with
>   any of the following names:
> 
>     HinnantDateConfig.cmake
>     hinnantdate-config.cmake
> 
>   Add the installation prefix of "HinnantDate" to CMAKE_PREFIX_PATH or set
>   "HinnantDate_DIR" to a directory containing one of the above files.  If
>   "HinnantDate" provides a separate development package or SDK, be sure it
>   has been installed.
> Call Stack (most recent call first):
>   vendor/sqlpp11/cmake/Sqlpp11Config.cmake:29 (find_dependency)
>   vendor/sqlpp11-connector-postgresql/CMakeLists.txt:32 (find_package)
> 
> 
> -- Configuring incomplete, errors occurred!

This all works when I install HinnantDate, sqlpp11, etc. to my system, but I want to have them install as submodules of my project to avoid polluting where it runs with lots of requirements.
Could anyone advise me on how to go about this?
Thanks,
   Doug.

**Comment by rbock** [comment] 2017-01-31 11:40
Hi,

I haven't tried that before, by I assume that you could set HinnantDate_DIR to something like "${CMAKE_CURRENT_SOURCE_DIR}/vendor/date"} in your main CMakeLists.txt

Hope that helps.

Best,

Roland

**Comment by biot023** [comment] 2017-01-31 15:40
Cheers, Roland -- I tried several variations on that theme, to no avail.
Currently it looks like this:

    set(Sqlpp11_DIR ${VENDOR_DIR}/sqlpp11/cmake)
    set(HinnantDate_ROOT_DIR vendor/date)
    set(HinnantDate_DIR vendor/date)
    add_subdirectory(vendor/date)
    add_subdirectory(vendor/sqlpp11)
    add_subdirectory(vendor/sqlpp11-connector-postgresql)

But I still get this error:

> CMake Error at /usr/local/share/cmake-3.7/Modules/CMakeFindDependencyMacro.cmake:55 (find_package):
>   By not providing "FindHinnantDate.cmake" in CMAKE_MODULE_PATH this project
>   has asked CMake to find a package configuration file provided by
>   "HinnantDate", but CMake did not find one.
> 
>   Could not find a package configuration file provided by "HinnantDate" with
>   any of the following names:
> 
>     HinnantDateConfig.cmake
>     hinnantdate-config.cmake
> 
>   Add the installation prefix of "HinnantDate" to CMAKE_PREFIX_PATH or set
>   "HinnantDate_DIR" to a directory containing one of the above files.  If
>   "HinnantDate" provides a separate development package or SDK, be sure it
>   has been installed.
> Call Stack (most recent call first):
>   vendor/sqlpp11/cmake/Sqlpp11Config.cmake:29 (find_dependency)
>   vendor/sqlpp11-connector-postgresql/CMakeLists.txt:32 (find_package)
> 
> 
> -- Configuring incomplete, errors occurred!

Is there a generally more accepted way of installing, then? I'll happily go with a standard! :)

**Comment by biot023** [comment] 2017-02-20 07:30
I've returned to this after a brief hiatus, but still to no avail.
I'm getting this error:

> CMake Error at vendor/sqlpp11/tests/CMakeLists.txt:51 (add_executable):
> Target "sqlpp11_tests" links to target "HinnantDate::Date" but the target
> was not found.  Perhaps a find_package() call is missing for an IMPORTED
> target, or an ALIAS target is missing?

The bit of my CMakeLists.txt that tries to install sqlpp11 looks like this:

    set(HinnantDate_ROOT_DIR vendor/date)
    set(HinnantDate_INCLUDE_DIR vendor/date)
    set(HinnantDate_DIR vendor/date)
    include_directories(${HinnantDate_INCLUDE_DIR})
    
    add_subdirectory(vendor/sqlpp11)

I'm absolutely stumped, and am going to have to look at another way of interacting with the database for now, but would be over the moon if someone could help me understand what I should be doing here for the next time I look into this.
Thanks for any and all help,
   Doug.

**Comment by rbock** [comment] 2017-02-20 09:19
Hi Doug,

here's what I tried:

```sh
git init
mkdir submodules
git submodule add https://github.com/HowardHinnant/date submodules/date
git submodule add https://github.com/rbock/sqlpp11 submodules/sqlpp11
git submodule add https://github.com/matthijs/sqlpp11-connector-postgresql submodules/sqlpp11-connector-postgresql
vim CMakeLists.txt # see below
mkdir build
cd build
cmake .. -DHinnantDate_ROOT_DIR=$PWD/../submodules/date
```

Works just fine. With the sqlite3 connector you don't even need to to set the `HinnantDate_ROOT_DIR`, because it assumes date to be located in the same root directory.

My `CMakeLists.txt`:

```cmake
cmake_minimum_required(VERSION 3.2 FATAL_ERROR)
project(biot VERSION 0.1 LANGUAGES CXX)

#add_subdirectory(submodules/sqlpp11-connector-sqlite3)
add_subdirectory(submodules/sqlpp11-connector-postgresql)
```

**Comment by biot023** [comment] 2017-02-20 09:42
I'll try that out on another branch when I can -- in the meantime, thanks so much for your help.
Doug.

**Comment by rahul-agrawal21** [comment] 2018-07-25 05:01
Hi Roland,
I followed the steps that worked for you, however I still get the errors mentioned in the very first comment.

**Comment by aminaramoon** [comment] 2019-03-22 01:09
having the same issue
nothign seems to work

**Comment by rbock** [comment] 2019-03-22 08:32
Hi,

I am very sorry, but my CMake skills are super limited. There might be an issue with the CMake scripts of the library. Or it is something you do in your scripts. I really don't know.

I am afraid you have to figure this out for yourself.

If it turns out to be an issue in the CMake scripts of the library, I'd be interested in a pull request.

Best,

Roland

**Comment by TimboKZ** [comment] 2019-07-14 20:47
I was experiencing the same issue. I spent hours trying different combinations, and following `CMakeLists.txt` worked for me in the end (using SQLite3 connector):
```cmake
cmake_minimum_required(VERSION 3.14)
project(ogma_backend)

set(CMAKE_CXX_STANDARD 14)

set(SRC_DIR "${PROJECT_SOURCE_DIR}/src")
set(LIB_DIR "${PROJECT_SOURCE_DIR}/libs")

include_directories(
        libs/date/include
        libs/date/include/date
        libs/sqlpp11/include
        libs/sqlpp11-connector-sqlite3/include
)

find_package(Boost 1.69 REQUIRED)
find_package(SQLite3 REQUIRED)

set(HinnantDate_ROOT_DIR "${LIB_DIR}/date/include")
set(Sqlite3_DIR "${LIB_DIR}/libsqlite3")
set(Sqlpp11_DIR "${LIB_DIR}/sqlpp11")
set(Sqlpp11Sqlite3_DIR "${LIB_DIR}/sqlpp11-connector-sqlite3")

add_subdirectory(${Sqlpp11_DIR})
add_subdirectory(${Sqlpp11Sqlite3_DIR})

file(
        GLOB Backend_SRC
        "${SRC_DIR}/*.h"
        "${SRC_DIR}/*.cpp"
        "${Sqlpp11Sqlite3_DIR}/src/*.h"
        "${Sqlpp11Sqlite3_DIR}/src/*.cpp"
        "${Sqlpp11Sqlite3_DIR}/src/detail/*.h"
        "${Sqlpp11Sqlite3_DIR}/src/detail/*.cpp"
)

add_executable(ogma_backend ${Backend_SRC})
target_link_libraries(ogma_backend sqlite3 sqlpp11)
```

My directory structure was:
```
.
├── CMakeLists.txt
├── libs
│   ├── date
│   ├── libsqlite3
│   ├── sqlpp11
│   └── sqlpp11-connector-sqlite3
└── src
    ├── main.cpp
    └── TabSample.h
```

It seems my main problem was setting `HinnantDate_ROOT_DIR` to point to the actual root of the Howard Hinnant's `date` repository, instead of pointing to `<root>/include`.

**Comment by rbock** [comment] 2019-08-20 09:42
afaict, this is fixed now.

Closing.

**Closed by rbock** 2019-08-20 09:42 UTC

**Comment by mastergberry** [comment] 2020-03-29 14:58
I know I'm digging this out of the grave here but I recently ran into this problem and the above solutions were not working for me.

I mostly reproduced @rbock's setup with a few small changes to it. Storing this here for my PR + to help anyone else who might need it.

```cmake
cmake_minimum_required(VERSION 3.2 FATAL_ERROR)
project(biot VERSION 0.1 LANGUAGES CXX)

add_subdirectory(submodules/sqlpp11)
add_subdirectory(submodules/sqlpp11-connector-postgresql)
```

Borrowing again from rbock for the complete setup:

```bash
git init
mkdir submodules
git submodule add https://github.com/HowardHinnant/date submodules/date
git submodule add https://github.com/rbock/sqlpp11 submodules/sqlpp11
git submodule add https://github.com/matthijs/sqlpp11-connector-postgresql submodules/sqlpp11-connector-postgresql
vim CMakeLists.txt # see above
# Fix the CMakeFiles.txt found in sqlpp11-connector-postgresql with my commit below...or just clone my copy in the first place (if PR not merged)
mkdir build
cd build
cmake .. -DHinnantDate_ROOT_DIR=$PWD/../submodules/date
```

I also had to make a small change to the postgresql connector which can be seen here (PR Submitted too): https://github.com/mastergberry/sqlpp11-connector-postgresql/commit/7e31fbbab07f276a01f46acb27edf11baa3331b1
