### ISSUE TITLE
about float_safe_ostringstream.h

### ISSUE THREAD

**Issue by qbgbmpty** [rbock/sqlpp11#498] opened 2023-06-29 17:17 UTC
Hi, I found that when I include `postgresql.h` using the current version, it calls `/sqlpp11/detail/float_safe_ostringstream.h` at line 131 in `sqlpp11/postgresql/prepared_statement.h` and generates the following error message:
`../third-party/sqlpp11/include/sqlpp11/postgresql/prepared_statement.h:131:17:   required from here
../third-party/sqlpp11/include/sqlpp11/detail/float_safe_ostringstream.h:59:9: error: no matching function for call to 'std::basic_ostringstream<char>::precision(const std::initializer_list<const long int>&)'
os.precision(old_precision);`

However, when I revert the version of sqlpp11 to `dfa297f06970df4d525e7d35c2fa78ea5331f69b` from February 10th, this issue disappears. Can you please tell me if I made a mistake somewhere, or if it's caused by some other problem?

Thank you.

**Comment by rbock** [comment] 2023-06-30 04:41
Thanks for the report!

@bloerwald FYI

I believe this is caused by line [57](https://github.com/rbock/sqlpp11/blob/26280d2678a6eef9135246d680796d1cd5942730/include/sqlpp11/detail/float_safe_ostringstream.h#L57):

```
auto const old_precision{os.precision(std::numeric_limits<T>::max_digits10)};
```

Depending on the C++ version this will be interpreted in different ways, see also https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2014/n3922.html

```
auto const old_precision = os.precision(std::numeric_limits<T>::max_digits10);
```

I committed a change.

@qbgbmpty Can you confirm this compiles for you?

Thanks,
Roland

**Comment by qbgbmpty** [comment] 2023-06-30 07:23
Yes, I have confirmed that the code compiles successfully. Thanks!

**Closed** 2024-03-30 08:24 UTC
