### ISSUE TITLE
Specialize exceptions for different run-time errors

### ISSUE THREAD

**Issue by bllngr** [rbock/sqlpp11#277] opened 2019-05-28 13:40 UTC
One thing most (all?) SQL libraries for C++ do is reporting run-time errors via a single ``std::exception`` derived class; requiring to parse the returned SQL error code or even error string to get specific details.

Since this lib focuses on type-safety, it would be great if there where specialized exceptions for different run-time error (classes), that could possible also report the erroneous attributes.

For example constraint violations (unique, foreign_key etc.), readonly violations, protocol errors etc. pp. could all be reported via distinct exceptions.

**Comment by rbock** [comment] 2019-05-28 14:12
I wonder if that would actually make much of a difference in how you deal with errors?

Obviously you _could_ treat a constraint violation in a different way than a protocol error, but would you? Your code can't really adjust itself and try again, can it?

I am really curious about this, as I am about to dramatically reduce the number exception classes in another project...

**Comment by Erroneous1** [comment] 2019-05-30 00:56
Perhaps a better solution would be some kind of extension to system_error
since you usually get at least one error code. This would allow you to
determine the cause for an error without needing a separate class. For that
matter, doing error_code variants for exception-less users could prove
useful. It is something that all of the connector implementers would have
to confirm to.

One possible time you'd have a different code path for a specific error is
duplicate key inserts.

**Comment by bllngr** [comment] 2019-06-21 08:37
> One possible time you'd have a different code path for a specific error is duplicate key inserts.

That's the scenario I had in mind. When an exception occurs while ``INSERT``ing rows, a protocol error would be handled differently than a constraint violation. If e.g. a unique constraint violation occurs, a new ID could be generated, or the user could be asked to supply a different value. For protocol errors, this doesn't make sense.

At the moment, it's not possible to find out which column(s) exactly conflict. Sure, you could query the DB first and check if there would be any conflicts, but that's not very C++ idiomatic IMHO.

[SRombauts/SQLiteCpp](https://github.com/SRombauts/SQLiteCpp) for example reports at least the [(extended) error codes](https://sqlite.org/c3ref/c_abort.html), which could be used for further analysis. With sqlpp11, it seems like parsing the error string is necessary to find out the exact violation.

As @Erroneous1 said, wrapping the (extended) error codes in some kind of ``system_error`` would probably already help a lot.

**Comment by rbock** [comment] 2019-08-20 14:39
I am not a fan of system_error. But the connectors could certainly extend sqlpp11::exception to transport error codes.
As this affects the connectors, I am closing the issue here and put it on the wish list I am compiling.

**Closed by rbock** 2019-08-20 14:39 UTC
