### ISSUE TITLE
how to fix update exception?

### ISSUE THREAD

**Issue by shishirong** [rbock/sqlpp11#561] opened 2024-03-14 08:11 UTC
```sql
CREATE TABLE users (
    id        INTEGER PRIMARY KEY AUTOINCREMENT,
    pid       INTEGER,
    user_id   TEXT,
    user_name TEXT,
    passwd    TEXT
);
```

```cpp
db(update(user).set(user.userName = "test",user.passwd = "test").where(user.userId == "123"));
```
on sqlite

update other table exception too.

**Comment by MeanSquaredError** [comment] 2024-03-16 01:43
You should provide more information, at least the exception message that you get.

**Comment by rbock** [comment] 2024-03-16 08:12
And with the exception message, please also provide a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example).

**Comment by shishirong** [comment] 2024-03-18 06:56
> You should provide more information, at least the exception message that you get.

sorry,the  exception message is:
```log
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
```


> And with the exception message, please also provide a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example).

minimal example:
[demo.zip](https://github.com/rbock/sqlpp11/files/14632129/demo.zip)

**Comment by MeanSquaredError** [comment] 2024-03-18 14:50
@shishirong 

I could not find any obvious problems after looking at your source code. 

So I built your project on latest Fedora 39. I had to rename `DBModels.h -> DbModels.h` because of filesystem case-sensitivity, but other than that, building the project went OK. After running the built executable it also worked fine and exited normally.

What platform you are building/running your demo on?

The error that you are getting `std::bad_alloc`, which implies some kind of memory problem, you are running out of memory or getting heap corruption.

I would check for a mismatch between sqlite3 library headers and the corresponding sqlite3 dynamic/static library. If that is OK, then probably the most straightforward approach would be to run it under your platform debugger to see where it throws `std::bad_alloc` and if there is any platform-specific error that is mapped to `std::bad_alloc`. If that doesn't help, then it probably makes sense to run it under a memory debugger like Valgrind.

**Comment by shishirong** [comment] 2024-03-19 00:10
![image](https://github.com/rbock/sqlpp11/assets/16620315/898b958c-863d-49e6-89c7-7b4b04025dd2)
os: windows 10 x64,
compiler: mingw81_64
sqlite and sqlpp11 version is in cmakelists.txt

when I select msvc as compiler,  problems disappear
![image](https://github.com/rbock/sqlpp11/assets/16620315/11b8598a-3cde-4d4d-9e68-9ddee31661c0)

how I can make corrections  on mingw81_64 compiler?

**Comment by MeanSquaredError** [comment] 2024-03-19 01:17
I don't have mingw on my Windows 10 machine at the moment, so I cannot test it.

My prime suspect is the sqlite3 library that is linked to your app. You may want to check if the sqlite3 headers are for the same version as the sqlite library that you are linking to your executable. Also make sure that the sqlite3 library uses the same CRT DLL as your main executable, so that you don't have two memory heaps. Maybe try using http://dependencywalker.com/ or another similar tool to check if the main executable and the sqlite3 library use the same CRT DLL.

**Comment by rbock** [comment] 2024-03-30 08:10
@shishirong Any updates?

**Comment by shishirong** [comment] 2024-04-02 02:57
The project is static link to sqlite library, I don't have any idea about sqlite3 library version and sqlite3 headers version
![image](https://github.com/rbock/sqlpp11/assets/16620315/4a049db8-e1a4-4aeb-ab6d-a2ff5fb3a50f)
![image](https://github.com/rbock/sqlpp11/assets/16620315/8c960a0f-9af6-43be-ab25-5635fd5d81bb)

**Comment by rbock** [comment] 2024-04-02 05:08
I cannot comment on the dependency walker, maybe @MeanSquaredError can help with that?

In the meantime:

* Can you run the sqlite3 tests that come with the sqlpp11 library?
* The example code you provided fails in the `CREATE TABLE` already. Can you re-write that using sqlite3 directly? Does that crash, too?

**Comment by MeanSquaredError** [comment] 2024-04-02 10:22
I have a machine with Windows 10, so I will install mingw-64 and will try reproducing the problem tomorrow. I will post an update here once I try the demo program on my computer.

**Comment by MeanSquaredError** [comment] 2024-04-02 10:39
Also from the screenshot of depwalker it seems that the program uses msvcrt.dll, the non-debug build of the crt library, which is a bit surprising given that you are making a debug build of your project.

Also it is probably worth opening the dependencies of the libgcc_s_seh-1.dll and libstdc++-6.dll in depwalker and checking if they don't import a different build of the msvcrt library.

**Comment by MeanSquaredError** [comment] 2024-04-06 05:38
OK, I tried installing mingw (the cygwin distribution) and the demo program worked correctly for me without crashing.

I couldn't find your distribution `mingw81_64` available for download, at least not from a trusted source, so I just went with the internet install of cygwin. From that distro I installed additionally gcc-core, g++, cmake, make and built the demo. It exited normally without any crashes. I tried it several times, but it just seems to work normally.

Here is my setup.

OS: Windows 10 64-bit
MinGW: Cygwin (internet installer)
G++ (GCC): 11.4.0
CMake: 3.28.3
GNU Make: 4.4.1

Just for your information, I also built the demo in MinGW with MSVC in debug mode and ran it. The program then complained that
```
DBModels::Users user;
```
is being accessed without being initialized first. So you could try changing it to
```
DBModels::Users user {};
```
and see if that will make a difference when running it on your computer.

**Comment by MeanSquaredError** [comment] 2024-04-06 17:20
OK, I think I found a (semi)decent download site for MinGW 8.1, so I will try it as well and will post an update.

**Comment by shishirong** [comment] 2024-04-08 02:10
very thanks, I tried build in terminal, it works;   I build with qt-creator before.

**Comment by rbock** [comment] 2024-04-08 04:27
Thanks for confirming the runtime issues to be resolved. You should try to figure out what happens in qt-creator, but that's out of scope for this library, of course.
@MeanSquaredError Thanks a lot for your support!

As for the new problem you are facing: That's a compile time issue, and the static asserts often explain the issue:

```
[...] static assertion failed: at least one required column is missing in set()
```

Unfortunately, I have not found a decent way to indicate the exact column, but looking at your code and the demo.zip you sent earlier: You are missing a value for the "pid" column.

**Closed** 2024-04-08 09:36 UTC

**Comment by MeanSquaredError** [comment] 2024-04-08 09:51
> You should try to figure out what happens in qt-creator

@rbock 
+1 to that because the problem could re-appear with the command-line build too and then the user would be back to square one without the ability to create a working build.

@shishirong 
The problem causing the update crash seems to be triggered by something in the build environment. Given that the command-line build works and the qt-creator build crashes, then it is one of the following:

1. Compiler/linker version.
2. Compiler/linker options used during the build.
3. Linked libraries.

So  if you are intereseted in troubleshooting this issue, then you could try the following.

1. Record the compiler/linker switches used by qt-creator. Its been quite a while since the last time when I used qt-creator, but I remember that it had a verbose build mode where you could see the exact command-line switches passed to the compiler/linker. I am not sure if the [advice here](https://qt-creator.qt-project.narkive.com/pDSKBbZU/enable-verbose-build-output) is still relevant but you could try it
2. Record the compiler/linker switches used by cmake/make by passing `-DCMAKE_VERBOSE_MAKEFILE=ON` to the initial cmake command
3. Compare the two sets of compiler/linker switches and try to find out which one(s) make the difference. It might be a long/tedious process but it is easy to execute and in the end it should tell you which one is the culprit.

**Comment by shishirong** [comment] 2024-04-08 11:36
@MeanSquaredError  I find the main difference is `CMAKE_BUILD_TYPE`,  if -DCMAKE_BUILD_TYPE=Debug will recurrence exception

**Comment by rbock** [comment] 2024-04-09 04:57
> yes, it is missing "pid" column; I don't know how to control generated `sqlpp::tag::require_insert`.

Columns require insert if they have no default (including auto increment) and are not marked to be nullable.

**Comment by shishirong** [comment] 2024-04-23 08:46
> > yes, it is missing "pid" column; I don't know how to control generated `sqlpp::tag::require_insert`.
> 
> Columns require insert if they have no default (including auto increment) and are not marked to be nullable.
```sql
CREATE TABLE users (
    id        INTEGER PRIMARY KEY AUTOINCREMENT,
    pid       INTEGER,
    user_id   TEXT,
    user_name TEXT,
    passwd    TEXT
);
```
I dont set `NOT NULL`, it don't should be `sqlpp::tag::require_insert`

**Comment by rbock** [comment] 2024-04-24 04:34
When I run your table definition through the code generator, I get this column struct for `pid`:

```C++
    struct Pid
    {
      struct _alias_t
      {
        static constexpr const char _literal[] =  "pid";
        using _name_t = sqlpp::make_char_sequence<sizeof(_literal), _literal>;
        template<typename T>
        struct _member_t
          {
            T pid;
            T& operator()() { return pid; }
            const T& operator()() const { return pid; }
          };
      };
      using _traits = sqlpp::make_traits<sqlpp::integer, sqlpp::tag::can_be_null>;
    };
```

You seem to be getting something different for `using _traits` line? What is the exact command you are using for the code generation?

**Comment by shishirong** [comment] 2024-04-24 10:17
> You seem to be getting something different for `using _traits` line? What is the exact command you are using for the code generation?

```
// generated by E:/.CPM_SOURCE_CACHE/sqlpp11/53edfea4b803fb5a9a646b29baed82aa8bcdcd10/scripts/sqlite2cpp.py ./0.sql ./DBModels DBModels
```
record in DBModels.h

**Comment by rbock** [comment] 2024-04-25 05:06
OK, we wandered far enough from the original topic of this issue :-)

I created #569
